[window]
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"
[scrolling]
history = 100000
[font]
size = 17
normal.family = "Hack"
[selection]
save_to_clipboard = true
[colors.primary]
background = "#dadada"
foreground = "#4e4e4e"
dim_foreground = "#616161"
bright_foreground = "#3a3a3a"
[colors.cursor]
text = "#dadada"
cursor = "#4e4e4e"
[colors.vi_mode_cursor]
text = "#dadada"
cursor = "#007299"
[colors.search.matches]
foreground = "#ffffff"
background = "#007299"
[colors.search.focused_match]
foreground = "#ffffff"
background = "#005f87"
[colors.footer_bar]
foreground = "#4e4e4e"
background = "#bcbcbc"
[colors.hints.start]
foreground = "#4e4e4e"
background = "#d7afaf"
[colors.hints.end]
foreground = "#4e4e4e"
background = "#d0d0d0"
[colors.selection]
text = "#4e4e4e"
background = "#bcdede"
[colors.normal]
black = "#4e4e4e"
red = "#af005f"
green = "#5f875f"
yellow = "#af5f00"
blue = "#007173"
magenta = "#870087"
cyan = "#008787"
white = "#e4e4e4"
[colors.bright]
black = "#626262"
red = "#d70087"
green = "#87af87"
yellow = "#dfbc72"
blue = "#5fafd7"
magenta = "#af5fff"
cyan = "#00afaf"
white = "#ffffff"
[colors.dim]
black = "#3a3a3a"
red = "#9B1D72"
green = "#719872"
yellow = "#BE9873"
blue = "#719899"
magenta = "#9A7599"
cyan = "#6FBCBD"
white = "#d0d0d0"
