set-option -g prefix C-Space
set-option -g default-terminal "tmux-256color"
set-option -g terminal-overrides "*:RGB"
set-option -g status-left-length 128
set-option -g renumber-windows on
set-option -g extended-keys on
set-option -g mouse on
set-option -g focus-events on
set-option -g status-interval 1
set-option -g status-right "#{?client_prefix,^@ ,}%a %d %b %H:%M"
set-option -g window-status-format "#I:#W#{window_flags}#{?#{!=:#{pane_current_command},fish},»,}"
set-option -g window-status-current-format "#I:#W#{window_flags}#{?#{!=:#{pane_current_command},fish},»,}"
set-option -g window-status-current-style "bold,reverse"
set-option -sg history-limit 100000
set-option -wg mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe "$(uname -s | grep -q Darwin && echo pbcopy || echo wl-copy)"
bind-key -n M-[ copy-mode
bind-key -n M-] paste-buffer -p
bind-key -n M-Space command-prompt -p "project pattern:" "run-shell -b 'fish -lc \"projectile %1\"'"
bind-key -n M-m command-prompt -p "help for:" "run-shell 'man \"%1\" 2>/dev/null || \"%1\" --help 2>&1'"
bind-key -n M-x confirm-before -p "kill-pane #P? (y/n)" kill-pane
bind-key -n M-c new-window
bind-key -n M-- switch-client -l
bind-key -n M-w choose-tree -Zs
bind-key -n M-p previous-window
bind-key -n M-n next-window
bind-key -n M-: command-prompt
bind-key -n M-h select-pane -L
bind-key -n M-j select-pane -D
bind-key -n M-k select-pane -U
bind-key -n M-l select-pane -R
bind-key -n M-z resize-pane -Z
bind-key -n M-< swap-window -d -t -1
bind-key -n M-> swap-window -d -t +1
bind-key v split-window -h
bind-key s split-window -v
bind-key x run-shell "tmux list-panes -s -F '##{pane_id}' | xargs -P0 -I{} tmux send-keys -t {} C-c"
bind-key r run-shell "tmux list-panes -s -F '##{pane_id}' | xargs -P0 -I{} tmux send-keys -t {} Up Enter"
bind-key C-Space send-prefix
