set-option -g prefix C-s
bind-key C-s send-prefix
set-option -g default-terminal "tmux-256color"
set-option -g terminal-overrides "*:RGB"
set-option -g status-left-length 128
set-option -g set-titles on
set-option -g base-index 1
set-option -g extended-keys on
set-option -g renumber-windows on
set-option -g visual-activity on
set-option -g focus-events on
set-option -g status-interval 5
set-option -g mouse on
set-option -g window-status-format "#I:#W#{window_flags}#{?#{!=:#{pane_current_command},fish},▸,}"
set-option -g window-status-current-format "#I:#W#{window_flags}#{?#{!=:#{pane_current_command},fish},▸,}"
set-option -g window-status-current-style "bg=colour138"
set-option -sg history-limit 100000
set-option -wg mode-keys vi
bind-key -n M-[ copy-mode
bind-key -n M-] paste-buffer -p
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe
bind-key -n M-Space command-prompt -p "project pattern:" "run-shell -b 'fish -lc \"projectile %1\"'"
bind-key h command-prompt -p "help for:" "run-shell -b '%1 --help || man %1 || %1 help'"
bind-key -n M-x confirm-before -p "kill-pane #P? (y/n)" kill-pane
bind-key -n M-c new-window
bind-key -n M-- switch-client -l
bind-key -n M-w choose-tree -Zs
bind-key -n M-p previous-window
bind-key -n M-n next-window
bind-key -n M-v split-window -h
bind-key -n M-s split-window -v
bind-key -n M-: command-prompt
bind-key -n M-h select-pane -L
bind-key -n M-j select-pane -D
bind-key -n M-k select-pane -U
bind-key -n M-l select-pane -R
bind-key r source-file ~/.tmux.conf
