set -g extended-keys on
set -g extended-keys-format csi-u
set -g focus-events on
set -g set-titles on
set -g status-left-length 128
set -g mouse on
set -g status-interval 5
set -g history-limit 100000
set -g renumber-windows on
set -gw mode-keys vi
%hidden yankcmd="command -v pbcopy >/dev/null && pbcopy || wl-copy"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "$yankcmd"
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe "$yankcmd"
bind -r < swap-window -d -t -1
bind -r > swap-window -d -t +1
bind -r C-p previous-window
bind -r C-n next-window
bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R
bind -n C-Space command-prompt -p "pattern*>" {
    set @projectile_pattern "%1"
    run-shell -b "bash -c 'projectile #{q:@projectile_pattern}'"
} # passes prompt input shell-quoted into the script
