#!/usr/bin/env bash
set -euo pipefail

readonly XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
readonly XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
readonly XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
readonly XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
readonly DOTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

mkdirs() {
    echo '> creating essential dirs'
    local -a xdg_dirs=("$XDG_DATA_HOME" "$XDG_CONFIG_HOME" "$XDG_STATE_HOME" "$XDG_CACHE_HOME")
    local -a home_dirs=(repos personal)
    mkdir -p "${xdg_dirs[@]}" "${home_dirs[@]/#/$HOME/}"
}

link_dotfiles() {
    echo '> linking dotfiles'
    local -a dotfiles=(ghostty fish nvim .tmux.conf .psqlrc .gitignore)
    for file in "${dotfiles[@]}"; do
        local src=$DOTDIR/$file dst
        [[ -d $src ]] && dst=$XDG_CONFIG_HOME/$file
        [[ -f $src ]] && dst=$HOME/$file
        [[ -n $dst ]] || { echo "! file not found: $src" >&2; return; }
        ln -sfn "$src" "$dst"
    done
}

setup_macos() {
    xcode-select -p &>/dev/null || { echo '> installing command line tools for xcode'; xcode-select --install; }
    command -v brew &>/dev/null || {
        echo '> installing homebrew'
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        eval "$(/opt/homebrew/bin/brew shellenv)"
    }

    local -a packages=(git tmux fish watch neovim tree ncdu ripgrep jq ghostty font-ubuntu-sans-mono)
    echo '> installing essential packages'
    brew update && brew install "${packages[@]}"
}

setup_linux() {
    sudo apt-get update && sudo apt-get upgrade -y
    local -a packages=(curl git tmux fish watch neovim tree ncdu ripgrep jq)
    echo "> installing essential packages"
    sudo apt-get install -y "${packages[@]}"
    sudo snap install ghostty --classic
}

configure_git() {
    echo '> configuring git'
    git config --global core.excludesFile "$HOME/.gitignore"
    git config --global push.autoSetupRemote true
    git config --global pull.rebase true
    git config --global diff.tool nvimdiff
    git config --global merge.tool nvimdiff
    git config --global mergetool.keepBackup false
}

configure_shell() {
    [[ $SHELL == */fish ]] && { echo '* default shell is already fish'; return 0; }
    local fish_path=$(command -v fish)
    [[ -n $fish_path ]] || { echo '! fish not found in path' >&2; return 1; }

    echo '> changing default shell to fish'
    grep -qxF "$fish_path" /etc/shells || echo "$fish_path" | sudo tee -a /etc/shells
    chsh -s "$fish_path"
    echo '* please log out and log back in for shell change to take effect'
}

main() {
    mkdirs && link_dotfiles
    case $(uname -s) in
        Darwin) setup_macos ;;
        Linux)  setup_linux ;;
        *)      echo '! unsupported os: only macos and linux' >&2; exit 1 ;;
    esac
    configure_git
    configure_shell
}

main "$@"
# vim: ft=bash
